image: dvmgremp/ansible-build:bookworm

pipelines:
    custom:
        build_deploy_docker:
            - step:
                name: "Build & Deploy Docker images"
                image: ubuntu:22.04
                script:
                    - chmod +x builds/*.sh
                    - sh builds/run.sh ansible
                    - sh builds/run.sh deploy
                    - sh builds/run.sh php
